# Generated by Django 5.0.4 on 2024-06-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_group_owner_group_privacy_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='image_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
