# Generated by Django 5.0.4 on 2024-06-14 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_userprofile_bio_alter_userprofile_facebook_url_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
