# Generated by Django 5.0.4 on 2024-06-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='contact_number',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='full_name',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
